version: '3.9'
services:

  # Nats
  nats-spot:
    image: nats:latest
    container_name: nats-spot
    ports:
      - 8222:8222
    volumes:
      - ./config-nats/:/etc/nats
    restart: always
    command: '-c /etc/nats/nats-server.conf'
    networks:
      - spot_net

  # Gateway
  spot-gateway:
    image: spot-ms-gateway:${APP_VERSION}
    container_name: spot-gateway
    build:
      context: ./spot-gateway
      target: dev
      dockerfile: Dockerfile
    env_file: ./spot-gateway/.env
    volumes:
      - ./spot-gateway/src:/usr/src/app/src
    restart: always
    ports:
      - ${PORT}:3000
    networks:
      - spot_net
    depends_on:
      - nats-spot

  # Auth
  spot-auth:
    image: spot-ms-auth:${APP_VERSION}
    container_name: spot-ms-auth
    build:
      context: ./spot-ms-auth
      target: dev
      dockerfile: Dockerfile
    env_file: ./spot-ms-auth/.env
    volumes:
      - ./spot-ms-auth/src:/usr/src/app/src
    restart: always
    networks:
      - spot_net
    depends_on:
      - nats-spot

  # User
  spot-users:
    image: spot-ms-users:${APP_VERSION}
    container_name: spot-ms-users
    build:
      context: ./spot-ms-users
      target: dev
      dockerfile: Dockerfile
    env_file: ./spot-ms-users/.env
    volumes:
      - ./spot-ms-users/src:/usr/src/app/src
    restart: always
    networks:
      - spot_net
    depends_on:
      - nats-spot

  # Emails
  spot-emails:
    image: spot-ms-emails:${APP_VERSION}
    container_name: spot-ms-emails
    build:
      context: ./spot-ms-emails
      target: dev
      dockerfile: Dockerfile
    env_file: ./spot-ms-emails/.env
    volumes:
      - ./spot-ms-emails/src:/usr/src/app/src
    restart: always
    networks:
      - spot_net
    depends_on:
      - nats-spot

  # Codes
  spot-codes:
    image: spot-ms-codes:${APP_VERSION}
    container_name: spot-ms-codes
    build:
      context: ./spot-ms-codes
      target: dev
      dockerfile: Dockerfile
    env_file: ./spot-ms-codes/.env
    volumes:
      - ./spot-ms-codes/src:/usr/src/app/src
    restart: always
    networks:
      - spot_net
    depends_on:
      - nats-spot

  # Notifications
  spot-notifications:
    image: spot-ms-notifications:${APP_VERSION}
    container_name: spot-ms-notifications
    build:
      context: ./spot-ms-notifications
      target: dev
      dockerfile: Dockerfile
    env_file: ./spot-ms-notifications/.env
    volumes:
      - ./spot-ms-notifications/src:/usr/src/app/src
    restart: always
    networks:
      - spot_net
    depends_on:
      - nats-spot

  # Parkings
  spot-parkings:
    image: spot-ms-parkings:${APP_VERSION}
    container_name: spot-ms-parkings
    build:
      context: ./spot-ms-parkings
      target: dev
      dockerfile: Dockerfile
    env_file: ./spot-ms-parkings/.env
    volumes:
      - ./spot-ms-parkings/src:/usr/src/app/src
    restart: always
    networks:
      - spot_net
    depends_on:
      - nats-spot

  # Currencies
  spot-currencies:
    image: spot-ms-currencies:${APP_VERSION}
    container_name: spot-ms-currencies
    build:
      context: ./spot-ms-currencies
      target: dev
      dockerfile: Dockerfile
    env_file: ./spot-ms-currencies/.env
    volumes:
      - ./spot-ms-currencies/src:/usr/src/app/src
    restart: always
    networks:
      - spot_net
    depends_on:
      - nats-spot

  # Facility
  spot-facilities:
    image: spot-ms-facilities:${APP_VERSION}
    container_name: spot-ms-facilities
    build:
      context: ./spot-ms-facilities
      target: dev
      dockerfile: Dockerfile
    env_file: ./spot-ms-facilities/.env
    volumes:
      - ./spot-ms-facilities/src:/usr/src/app/src
    restart: always
    networks:
      - spot_net
    depends_on:
      - nats-spot

  # Files
  spot-files:
    image: spot-ms-files:${APP_VERSION}
    container_name: spot-ms-files
    build:
      context: ./spot-ms-files
      target: dev
      dockerfile: Dockerfile
    env_file: ./spot-ms-files/.env
    volumes:
      - ./spot-ms-files/src:/usr/src/app/src
    restart: always
    networks:
      - spot_net
    depends_on:
      - nats-spot


networks:
  spot_net:
    name: spot_net